################################# Default configuration ###################
baseURL = "https://new.ra-pfeil.de"
title = "Kanzlei Hartmut Pfeil & Norman Noczinski"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
DefaultContentLanguage = "de"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "Über uns"
URL = "about"
weight = 1

[[menu.main]]
name = "Unsere Dienstleistungen"
URL = "services"
weight = 2

[[menu.main]]
name = "Anwälte"
URL = "team"
weight = 3

[[menu.main]]
name = "Pricing"
URL = "pricing"
weight = 4

[[menu.main]]
name = "Neuigkeiten"
URL = "blog"
weight = 5

[[menu.main]]
name = "Kontakt"
URL = "contact"
weight = 6

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Norman Noczinski"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBUsTC8eIsYbhj6nK09CByrCGIQfQKvGM0"
map_latitude = "52.5587242"
map_longitude = "13.4139481"
map_marker = "images/marker.png"

############################# social icons ##########################
#TODO! Update of the social pack makes sense.
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "https://www.linkedin.com/in/norman-noczinski-ab17b4a9/"
#
#[[params.social]]
#icon = "ti-xing" # themify icon pack : https://themify.me/themify-icons
#link = "https://www.xing.com/profile/Norman_Noczinski"

################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 1
home = "Startseite"
