name: GitHub Page Deploy

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build
        run: |
          hugo
        env:
          GOGGLE_MAPS_API_KEY: ${{ secrets.GOGGLE_MAPS_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
